let a=12;
let b=13;
let sum=a+b;
let sub=a-b;
let mul=a*b;
let div=a/b;
let mod=a%b;
let power=a**b;
console.log(`The sum of a and b is ${sum}`);
console.log(`The sub of a and b is ${sub}`);
console.log(`The mul of a and b is ${mul}`);
console.log(`The div of a and b is ${div}`);
console.log(`The mod of a and b is ${mod}`);
console.log(`The power of a and b is ${power}`);